name: Fast Request Handler Service CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'fast-requesthandler-service/**'
      - '.github/workflows/fast-requesthandler-service.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'fast-requesthandler-service/**'
      - '.github/workflows/fast-requesthandler-service.yml'

env:
  SERVICE_NAME: fast-requesthandler-service
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: gppg3/fast-requesthandler-service

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # Cloud Spanner Emulator
      spanner-emulator:
        image: gcr.io/cloud-spanner-emulator/emulator:latest
        ports:
          - 9010:9010
          - 9020:9020
        options: >-
          --health-cmd "curl -f http://localhost:9020 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 10s

      # Kafka with Zookeeper
      zookeeper:
        image: confluentinc/cp-zookeeper:7.4.0
        ports:
          - 2181:2181
        env:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000

      kafka:
        image: confluentinc/cp-kafka:7.4.0
        ports:
          - 9092:9092
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        options: >-
          --health-cmd "kafka-topics --bootstrap-server localhost:9092 --list || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 30s

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '${{ env.SERVICE_NAME }}/package-lock.json'

      - name: Install dependencies
        working-directory: ${{ env.SERVICE_NAME }}
        run: npm ci

      - name: Generate Protocol Buffers
        working-directory: ${{ env.SERVICE_NAME }}
        run: npm run proto:generate

      - name: Run linting
        working-directory: ${{ env.SERVICE_NAME }}
        run: npm run lint

      - name: Build TypeScript
        working-directory: ${{ env.SERVICE_NAME }}
        run: npm run build

      - name: Run unit tests
        working-directory: ${{ env.SERVICE_NAME }}
        run: npm test

      - name: Wait for Kafka to be ready
        run: |
          # Function to get Kafka container with robust identification
          get_kafka_container() {
            # Try multiple methods to identify the correct Kafka container
            local container_id=""
            
            # Method 1: Try GitHub Actions service label (most specific)
            container_id=$(docker ps -q --filter "ancestor=confluentinc/cp-kafka:7.4.0" --filter "label=com.github.actions.service=kafka" | head -1)
            
            # Method 2: Filter by exposed port (Kafka typically on 9092)
            if [ -z "$container_id" ]; then
              container_id=$(docker ps -q --filter "ancestor=confluentinc/cp-kafka:7.4.0" --filter "publish=9092" | head -1)
            fi
            
            # Method 3: Get the most recently created container with the image
            if [ -z "$container_id" ]; then
              container_id=$(docker ps -q --filter "ancestor=confluentinc/cp-kafka:7.4.0" --format "table {{.ID}}\t{{.CreatedAt}}" | sort -k2 -r | head -1 | cut -f1)
            fi
            
            # Method 4: Fallback to first container (with validation)
            if [ -z "$container_id" ]; then
              all_containers=$(docker ps -q --filter "ancestor=confluentinc/cp-kafka:7.4.0")
              container_count=$(echo "$all_containers" | wc -l)
              if [ "$container_count" -eq 1 ]; then
                container_id="$all_containers"
              elif [ "$container_count" -gt 1 ]; then
                echo "Warning: Multiple Kafka containers found. Using the first one."
                container_id=$(echo "$all_containers" | head -1)
              fi
            fi
            
            echo "$container_id"
          }
          
          KAFKA_CONTAINER=$(get_kafka_container)
          if [ -z "$KAFKA_CONTAINER" ]; then
            echo "Error: No Kafka container found!"
            echo "Available containers:"
            docker ps --filter "ancestor=confluentinc/cp-kafka:7.4.0"
            exit 1
          fi
          
          echo "Using Kafka container: $KAFKA_CONTAINER"
          echo "Container details:"
          docker inspect "$KAFKA_CONTAINER" --format '{{.Name}} ({{.Config.Image}})'
          
          timeout 60 bash -c "until docker exec $KAFKA_CONTAINER kafka-topics --bootstrap-server localhost:9092 --list >/dev/null 2>&1; do echo 'Waiting for Kafka...'; sleep 5; done"
          echo "Kafka is ready!"

      - name: Create Kafka topics
        run: |
          # Function to get Kafka container with robust identification  
          get_kafka_container() {
            # Try multiple methods to identify the correct Kafka container
            local container_id=""
            
            # Method 1: Try GitHub Actions service label (most specific)
            container_id=$(docker ps -q --filter "ancestor=confluentinc/cp-kafka:7.4.0" --filter "label=com.github.actions.service=kafka" | head -1)
            
            # Method 2: Filter by exposed port (Kafka typically on 9092)
            if [ -z "$container_id" ]; then
              container_id=$(docker ps -q --filter "ancestor=confluentinc/cp-kafka:7.4.0" --filter "publish=9092" | head -1)
            fi
            
            # Method 3: Get the most recently created container with the image
            if [ -z "$container_id" ]; then
              container_id=$(docker ps -q --filter "ancestor=confluentinc/cp-kafka:7.4.0" --format "table {{.ID}}\t{{.CreatedAt}}" | sort -k2 -r | head -1 | cut -f1)
            fi
            
            # Method 4: Fallback to first container (with validation)
            if [ -z "$container_id" ]; then
              all_containers=$(docker ps -q --filter "ancestor=confluentinc/cp-kafka:7.4.0")
              container_count=$(echo "$all_containers" | wc -l)
              if [ "$container_count" -eq 1 ]; then
                container_id="$all_containers"
              elif [ "$container_count" -gt 1 ]; then
                echo "Warning: Multiple Kafka containers found. Using the first one."
                container_id=$(echo "$all_containers" | head -1)
              fi
            fi
            
            echo "$container_id"
          }
          
          KAFKA_CONTAINER=$(get_kafka_container)
          if [ -z "$KAFKA_CONTAINER" ]; then
            echo "Error: No Kafka container found!"
            echo "Available containers:"
            docker ps --filter "ancestor=confluentinc/cp-kafka:7.4.0"
            exit 1
          fi
          
          echo "Using Kafka container: $KAFKA_CONTAINER"
          echo "Creating Kafka topics..."
          
          docker exec $KAFKA_CONTAINER kafka-topics --create --topic pacs-response-messages --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1 || true
          docker exec $KAFKA_CONTAINER kafka-topics --create --topic pacs-messages --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1 || true
          
          echo "Kafka topics created successfully!"

      - name: Setup database
        working-directory: ${{ env.SERVICE_NAME }}
        run: |
          # Wait for Spanner emulator to be ready
          timeout 60 bash -c 'until curl -f http://localhost:9020; do sleep 5; done'
          npm run db:setup
        env:
          SPANNER_EMULATOR_HOST: localhost:9010
          SPANNER_PROJECT_ID: test-project
          SPANNER_INSTANCE_ID: test-instance
          SPANNER_DATABASE_ID: test-database

      - name: Start service in background
        working-directory: ${{ env.SERVICE_NAME }}
        run: |
          npm run dev &
          SERVICE_PID=$!
          echo "SERVICE_PID=$SERVICE_PID" >> $GITHUB_ENV
          # Wait for service to start (gRPC health check)
          timeout 30 bash -c 'until grpc_health_probe -addr=localhost:50051 -service=gpp.g3.requesthandler.MessageHandler; do sleep 2; done'
        env:
          NODE_ENV: test
          PORT: 3001
          GRPC_PORT: 50051
          SPANNER_EMULATOR_HOST: localhost:9010
          SPANNER_PROJECT_ID: test-project
          SPANNER_INSTANCE_ID: test-instance
          SPANNER_DATABASE_ID: test-database
          KAFKA_BROKERS: localhost:9092

      - name: Install grpc_health_probe
        run: |
          wget -qO /usr/local/bin/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/v0.4.22/grpc_health_probe-linux-amd64
          chmod +x /usr/local/bin/grpc_health_probe

      - name: Install Playwright browsers
        working-directory: ${{ env.SERVICE_NAME }}
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: ${{ env.SERVICE_NAME }}
        run: npm run test:e2e
        env:
          NODE_ENV: test
          SPANNER_EMULATOR_HOST: localhost:9010
          SPANNER_PROJECT_ID: test-project
          SPANNER_INSTANCE_ID: test-instance
          SPANNER_DATABASE_ID: test-database
          KAFKA_BROKERS: localhost:9092
          SERVICE_URL: http://localhost:3001
          GRPC_URL: localhost:50051

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ env.SERVICE_NAME }}
          path: ${{ env.SERVICE_NAME }}/playwright-report/
          retention-days: 30

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ env.SERVICE_NAME }}
          path: ${{ env.SERVICE_NAME }}/test-results/
          retention-days: 30

      - name: Stop service
        if: always()
        run: |
          if [ ! -z "$SERVICE_PID" ]; then
            kill $SERVICE_PID || true
          fi

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ env.SERVICE_NAME }}
          file: ./${{ env.SERVICE_NAME }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate deployment artifact
        run: |
          mkdir -p deployment
          cat > deployment/docker-compose.yml << EOF
          version: '3.8'
          services:
            ${{ env.SERVICE_NAME }}:
              image: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
              ports:
                - "3001:3001"
                - "50051:50051"
              environment:
                - NODE_ENV=production
                - PORT=3001
                - GRPC_PORT=50051
              healthcheck:
                test: ["CMD", "grpc_health_probe", "-addr=localhost:50051", "-service=gpp.g3.requesthandler.MessageHandler"]
                interval: 30s
                timeout: 10s
                retries: 3
                start_period: 30s
          EOF

      - name: Upload deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment-${{ env.SERVICE_NAME }}
          path: deployment/
          retention-days: 30

  integration-test:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download deployment artifact
        uses: actions/download-artifact@v4
        with:
          name: deployment-${{ env.SERVICE_NAME }}
          path: deployment/

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install grpc_health_probe for integration tests
        run: |
          wget -qO /usr/local/bin/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/v0.4.22/grpc_health_probe-linux-amd64
          chmod +x /usr/local/bin/grpc_health_probe

      - name: Run integration tests with built image
        run: |
          cd deployment
          docker-compose up -d

          # Wait for service to be healthy (gRPC health check)
          timeout 60 bash -c 'until grpc_health_probe -addr=localhost:50051 -service=gpp.g3.requesthandler.MessageHandler; do sleep 5; done'

          # Run basic smoke tests
          echo "Running smoke tests..."
          grpc_health_probe -addr=localhost:50051 -service=gpp.g3.requesthandler.MessageHandler || exit 1

          # Cleanup
          docker-compose down -v
        env:
          DOCKER_REGISTRY: ${{ env.DOCKER_REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}

  deploy-staging:
    runs-on: ubuntu-latest
    needs: integration-test
    if: github.ref == 'refs/heads/develop'
    environment: staging

    steps:
      - name: Deploy to staging
        run: |
          echo "Deploying ${{ env.SERVICE_NAME }} to staging environment"
          echo "Image: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          # Add your staging deployment logic here

  deploy-production:
    runs-on: ubuntu-latest
    needs: integration-test
    if: github.ref == 'refs/heads/main'
    environment: production

    steps:
      - name: Deploy to production
        run: |
          echo "Deploying ${{ env.SERVICE_NAME }} to production environment"
          echo "Image: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          # Add your production deployment logic here 